### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by noahch** [yrutis/movie-recommender-system#2]
**User Story:**
As a user, I want to log in, such that I can access membership functionalities.

**Sub-Tasks**

- [ ] Create Login Form (frontend)
- [ ] Redirect to member area (frontend)
- [ ] Provide endpoint for login (member backend)
- [ ] Check permissions on API Endpoints (member backend)
- [ ] Document
