### ISSUE TITLE
User Signup

### ISSUE THREAD

**Issue by noahch** [yrutis/movie-recommender-system#3]
**User Story**
As a user, I want to register/sign up, such that I can access membership functionalities in the future.

**Sub-Tasks**
- [x]  Create Signup Form (frontend)
- [x]  Redirect to member area (frontend)
- [x]  Provide endpoint for user creation (member backend)
- [x]  Save new users in the database (member backend)
- [x]  Document
